"""add and fix entities, models and mappers

Revision ID: 2aeff294ff24
Revises: 0eb2d47d3797
Create Date: 2026-03-19 17:12:40.078389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aeff294ff24'
down_revision: Union[str, Sequence[str], None] = '0eb2d47d3797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'approved', 'rejected', name='milestone_status'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_milestones_check_amount_non_negative')),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name=op.f('ck_milestones_check_progress_percentage_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)

    op.create_table('proposals',
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('estimated_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'accepted', 'rejected', 'withdrawn', name='proposal_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('estimated_budget >= 0', name=op.f('ck_proposals_check_estimated_budget_non_negative')),
    sa.CheckConstraint('estimated_hours >= 0', name=op.f('ck_proposals_check_estimated_hours_non_negative')),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], name=op.f('fk_proposals_freelancer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_proposals_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_freelancer_id'), ['freelancer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_project_id'), ['project_id'], unique=False)

    op.create_table('time_entries',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', name='time_entry_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('freelancer_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hours <= 24', name=op.f('ck_time_entries_check_hours_daily_limit')),
    sa.CheckConstraint('hours >= 0', name=op.f('ck_time_entries_check_hours_non_negative')),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], name=op.f('fk_time_entries_freelancer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_time_entries_milestone_id_milestones'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_time_entries_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entries'))
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_freelancer_id'), ['freelancer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_project_id'), ['project_id'], unique=False)

    op.create_table('reviews',
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('communication_rating', sa.Float(), nullable=False),
    sa.Column('quality_rating', sa.Float(), nullable=False),
    sa.Column('deadline_rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('reviewee_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('communication_rating >= 1 AND communication_rating <= 5', name=op.f('ck_reviews_check_communication_rating_range')),
    sa.CheckConstraint('deadline_rating >= 1 AND deadline_rating <= 5', name=op.f('ck_reviews_check_deadline_rating_range')),
    sa.CheckConstraint('quality_rating >= 1 AND quality_rating <= 5', name=op.f('ck_reviews_check_quality_rating_range')),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_check_rating_range')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_reviews_contract_id_contracts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reviews_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], name=op.f('fk_reviews_reviewee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewee_id'), ['reviewee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('notifications',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('project_invitation', 'proposal_received', 'contract_signed', 'invoice_issued', 'payment_received', 'milestone_completed', 'review_received', name='notification_type'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('notification_metadata', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('contract_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_notifications_contract_id_contracts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_notifications_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notifications_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('draft', 'sent', 'signed', 'active', 'completed', 'terminated', name='contract_status'), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('termination_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('proposal_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('terms',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_contracts_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_contracts_proposal_id_proposals'), 'proposals', ['proposal_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('milestone_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('issued_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_invoices_freelancer_id'))
        batch_op.create_index(batch_op.f('ix_invoices_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_invoices_invoice_number'), ['invoice_number'])
        batch_op.drop_constraint(batch_op.f('fk_invoices_freelancer_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invoices_milestone_id_milestones'), 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('freelancer_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('skills_required', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_remote', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.alter_column('budget',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_projects_freelancer_id'))
        batch_op.create_unique_constraint('uq_title', ['title'])
        batch_op.drop_constraint(batch_op.f('fk_projects_freelancer_id_users'), type_='foreignkey')
        batch_op.drop_column('freelancer_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('is_available')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('skills')
        batch_op.drop_column('bio')
        batch_op.drop_column('phone')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freelancer_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_projects_freelancer_id_users'), 'users', ['freelancer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_title', type_='unique')
        batch_op.create_index(batch_op.f('ix_projects_freelancer_id'), ['freelancer_id'], unique=False)
        batch_op.alter_column('budget',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('is_remote')
        batch_op.drop_column('location')
        batch_op.drop_column('skills_required')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freelancer_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_invoices_milestone_id_milestones'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invoices_freelancer_id_users'), 'users', ['freelancer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(batch_op.f('uq_invoices_invoice_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_invoices_milestone_id'))
        batch_op.create_index(batch_op.f('ix_invoices_freelancer_id'), ['freelancer_id'], unique=False)
        batch_op.alter_column('issued_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('milestone_id')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('notes')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('invoice_number')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contracts_proposal_id_proposals'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_proposal_id'))
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('terms',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('proposal_id')
        batch_op.drop_column('termination_reason')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('signed_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_project_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_contract_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewee_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_project_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_contract_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_freelancer_id'))

    op.drop_table('time_entries')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_project_id'))
        batch_op.drop_index(batch_op.f('ix_proposals_freelancer_id'))

    op.drop_table('proposals')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))

    op.drop_table('milestones')
    # ### end Alembic commands ###
