"""add missing constraints

Revision ID: bd1b6f99b1e5
Revises: 426b77623444
Create Date: 2026-03-11 12:29:23.335833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1b6f99b1e5'
down_revision: Union[str, Sequence[str], None] = '426b77623444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_clients_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('owner_id', 'name', name='uq_client_owner_name')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_owner_id'), ['owner_id'], unique=False)

    op.create_table('projects',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'cancelled', name='project_status'), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('budget >= 0', name=op.f('ck_projects_check_budget_non_negative')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_projects_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], name=op.f('fk_projects_freelancer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_freelancer_id'), ['freelancer_id'], unique=False)

    op.create_table('contracts',
    sa.Column('terms', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('value >= 0', name=op.f('ck_contracts_check_value_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_contracts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_project_id'), ['project_id'], unique=False)

    op.create_table('invoices',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'pending', 'paid', 'overdue', 'cancelled', name='invoice_status'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_invoices_check_amount_non_negative')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_invoices_contract_id_contracts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_contract_id'), ['contract_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_unique_constraint('uq_email', ['email'])
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')
        batch_op.drop_constraint('uq_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_contract_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_project_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_freelancer_id'))
        batch_op.drop_index(batch_op.f('ix_projects_client_id'))

    op.drop_table('projects')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_owner_id'))

    op.drop_table('clients')
    # ### end Alembic commands ###
