"""add Multi-Tenant Data Isolation

Revision ID: d036e04596ff
Revises: bd1b6f99b1e5
Create Date: 2026-03-11 12:43:38.427038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd036e04596ff'
down_revision: Union[str, Sequence[str], None] = 'bd1b6f99b1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freelancer_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_contracts_freelancer_id'), ['freelancer_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_contracts_freelancer_id_users'), 'users', ['freelancer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freelancer_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_invoices_freelancer_id'), ['freelancer_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_invoices_freelancer_id_users'), 'users', ['freelancer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoices_freelancer_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_freelancer_id'))
        batch_op.drop_column('freelancer_id')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contracts_freelancer_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_freelancer_id'))
        batch_op.drop_column('freelancer_id')

    # ### end Alembic commands ###
